#!/bin/bash

set +e

bootanim=""
failcounter=0

adb="${ANDROID_HOME}/platform-tools/adb"
device="emulator-5554"
timeout_in_sec=360

while getopts a:t:d flag; do
  case "${flag}" in
      a) adb=${OPTARG};;
      d) device=${OPTARG};;
      t) timeout_in_sec=${OPTARG};;
  esac
done

until [[ "$bootanim" =~ "stopped" ]]; do
  bootanim=`$adb -s $device -e shell getprop init.svc.bootanim 2>&1 &`
  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    if [[ $failcounter = 1 ]]; then
      echo -n "Waiting for emulator to start"; else
      echo -n "."
    fi
    if [[ $failcounter -gt timeout_in_sec ]]; then
      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
      exit 1
    fi
  fi
  sleep 1
done

echo "Emulator is ready"
